name: GXPEclagg
description: Recoded & improved auto clear lagg plugin

main: twisted\autoclearlagg\AutoClearLagg
version: 3.0.0
api: [3.0.0]

author: Twisted
website: https://github.com/TwistedAsylumMC/AutoClearLagg
