---
# AutoClearLagg (ACL) Config

# Seconds between each clear lagg
seconds: 260

# Entities to clear
clear:
  items: true
  mobs: true
  exempt: # Array of entities not to clear
    - Zombie
    - Pig

messages:
  time-left: "§8[§3GXPE§8]§bEntities will clear in §3{SECONDS} seconds"
  entities-cleared: "§8[§3GXPE§8] §bCleared a total of §3{COUNT} entities"

# Countdown times
times: [90, 60, 30, 15, 10, 5, 4, 3, 2, 1]
...
